name: Subdomain Enumeration

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Target domain (e.g., example.com)'
        required: true
        default: 'example.com'

jobs:
  enumerate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install Tools
        run: |
          go install github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
          go install github.com/projectdiscovery/dnsx/cmd/dnsx@latest
          wget https://github.com/d3mondev/puredns/releases/latest/download/puredns-linux-amd64 -O puredns
          chmod +x puredns && sudo mv puredns /usr/local/bin

      - name: Download Public Resolvers
        run: |
          mkdir -p wordlists
          curl -sSL https://raw.githubusercontent.com/projectdiscovery/public-resolvers/main/resolvers.txt -o wordlists/resolvers.txt

      - name: Run Enumeration
        run: |
          chmod +x subenum.sh
          ./subenum.sh ${{ github.event.inputs.domain }}

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: subdomain-results
          path: output/${{ github.event.inputs.domain }}
