name: Subdomain Enumeration

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Target domain (e.g., example.com)'
        required: true
        default: 'example.com'

jobs:
  enumerate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false

      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential
          go install github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
          go install github.com/projectdiscovery/dnsx/cmd/dnsx@latest
          git clone https://github.com/blechschmidt/massdns.git
          cd massdns && make && sudo cp bin/massdns /usr/local/bin && cd ..
        # go install github.com/d3mondev/puredns/v2@latest

      # - name: Download Public Resolvers
      #   run: |
      #     mkdir -p wordlists
      #     curl -sSL https://raw.githubusercontent.com/projectdiscovery/public-resolvers/main/resolvers.txt -o wordlists/resolvers.txt

      - name: Run Enumeration
        run: |
          chmod +x subenum.sh
          ./subenum.sh ${{ github.event.inputs.domain }}

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: subdomain-results
          path: output/${{ github.event.inputs.domain }}
